# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 25b854132915a9a983f04b5d37008e92280da69f421f721b59c94ae9cbdbc01046bc3b3140913e6b3fcec9d8fb4091c9add96b6fdfae297e50eeae94cdbb0b91

test:
  secret_key_base: 3f4c7af0062881740065612eaa1f770de8eb130683b8dd2db7cfea916472d8043425b81c9d095eff923fd0292f4338a0d02d5272b1cc820032240e4d66bca656

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
